apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a2lybkjzo-python
  janus-idp.io/tekton: a2lybkjzo-python
  backstage.io/kubernetes-id: a2lybkjzo-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a2lybkjzo-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
